### ISSUE TITLE
validation of haproxy configuration fails

### ISSUE THREAD

**Issue by akhon** [Oefenweb/ansible-rsyslog#10]
having haproxy config similar to the config in readme, and validation fails by some reason:

```
# rsyslogd -N1 -f /etc/rsyslog.d/49-haproxy.conf
rsyslogd: version 8.2001.0, config validation run (level 1), master config /etc/rsyslog.d/49-haproxy.conf
rsyslogd: invalid or yet-unknown config file command 'AddUnixListenSocket' - have you forgotten to load a module? [v8.2001.0 try https://www.rsyslog.com/e/3003 ]
# rsyslogd -N1 -f /etc/rsyslog.d/49-haproxy.conf
```

OS: Ubuntu 20.04 LTS

**Comment by akhon** [comment]
and rsyslog works with that config. weird.

**Comment by tersmitten** [comment]
```yml
rsyslog_rsyslog_d_presets_49_haproxy:
  settings:
    # Create an additional socket in haproxy's chroot in order to allow logging via
    # /dev/log to chroot'ed HAProxy processes
    - '$AddUnixListenSocket /var/lib/haproxy/dev/log'
  rules:
    # Send HAProxy messages to a dedicated logfile
    - rule: ':programname, isequal, "haproxy"'
      logpath: /var/log/haproxy.log
  directives:
    - '& ~'
  # Does not validate in Ubuntu 16.04, because of the `$AddUnixListenSocket`?
  validate: "{{ ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('16.04', '<') }}"
```

This is what I'm using
