### ISSUE TITLE
Configuration validation fails on file with rsyslog 8.2001.0

### ISSUE THREAD

**Issue by yoannrt** [Oefenweb/ansible-rsyslog#14]
# Bug description

When I use rsyslog_rsyslog_d_files: to generate a config file under /etc/rsyslog.d/ I get the followind error on validation step 
```
- name: update specific configuration files
  template:
    src: etc/rsyslog.d/rsyslog.conf.j2
    dest: "/etc/rsyslog.d/{{ item.key }}.conf"
    validate: "{{ 'rsyslogd -N1 -f %s' if item.value.validate | default(true) else 'true %s' }}"
```
```
rsyslogd: imfile: no working or state file directory set, imfile will create state files in the current working directory (probably the root dir). Use global(workDirectory="/some/path") to set the working directory [v8.2001.0 try https://www.rsyslog.com/e/2450 ]
```

# Environnement

Occurs on Ubuntu 20.04 with rsyslogd version 8.2001.0

# Workaround

The only workaround I found for the moment is to add the parameter WorkDirectory in the config file (even if the parameter is already set under /etc/rsyslog.conf)

```
rsyslog_rsyslog_d_presets_23_fail2ban:
  rules:
    - rule: '$ModLoad'
      logpath: 'imfile'
    - rule: '$WorkDirectory'
      logpath: '/var/spool/rsyslog'
```

I searched a bit for a cleaner workaround or fix but I'm stuck on this. Maybe anyone has an idea to fix this ?

**Comment by akhon** [comment]
you can set validate: false for now

**Comment by tersmitten** [comment]
Indeed. I did something sililar in the past:

```
rsyslog_rsyslog_d_presets_49_haproxy:
  settings:
    # Create an additional socket in haproxy's chroot in order to allow logging via
    # /dev/log to chroot'ed HAProxy processes
    - '$AddUnixListenSocket /var/lib/haproxy/dev/log'
  rules:
    # Send HAProxy messages to a dedicated logfile
    - rule: ':programname, isequal, "haproxy"'
      logpath: /var/log/haproxy.log
  directives:
    - '& ~'
  # Does not validate in Ubuntu 16.04, because of the `$AddUnixListenSocket`?
  validate: "{{ ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('16.04', '<') }}"
```
