### ISSUE TITLE
Make apt (install) state configurable

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-rsyslog#8]
Since this is an Ansible best practice, making it configurable would a  nice feature.

```
  apt:
    name: rsyslog
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
```

Should work nice with our [apt role](https://github.com/Oefenweb/ansible-apt)
